[theme]
base                     = "light"
primaryColor             = "#4f46e5"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor                = "#1e1e2e"
font                     = "sans serif"

[server]
runOnSave                = true

[browser]
gatherUsageStats         = false
